### ISSUE TITLE
Andrew and acid

### ISSUE THREAD

**Issue by call-me-Neuro** [Nps-rf/YandexInternship2022#1]
длина set может быть меньше обычной длины поэтому будут ошибки например
5
1 1 5 3 5 ответ будет 4, хотя должен быть -1 или я что-то не так понимаю?

**Comment by Nps-rf** [comment]
И правда...
Тема с set была придумана в надежде на оптимизацию работы кода, я тоже об этом задумывался, но тесты яндекса это не покрывали, поэтому я решил не трогать, если это работало :)

**Comment by Nps-rf** [comment]
@Vasneuro 
Исправил в 5f0e5ab

**Comment by banrj** [comment]
почему мы не может уровнять вторую строку с помощью двух операций по 4 литра, почему мы не может уровнять 3 строку с помощью 3 операций по 1 литру, читаю условие и не могу вникнуть.
Объясните пожалуйста

**Comment by Nps-rf** [comment]
> почему мы не может уровнять вторую строку с помощью двух операций по 4 литра, почему мы не может уровнять 3 строку с помощью 3 операций по 1 литру, читаю условие и не могу вникнуть. Объясните пожалуйста

**Стоило бы** открыть **новый** вопрос, но отвечу тут.
[Входные данные №3](https://github.com/Nps-rf/YandexInternship2022#:~:text=1%205%205%205-,%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%203,-%D0%92%D0%B2%D0%BE%D0%B4)
Данные: `3 2 1`  Ответ: `-1`
Обратимся к [условию задачи](https://github.com/Nps-rf/YandexInternship2022#:~:text=%D0%9A%20%D1%81%D0%BE%D0%B6%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E%2C%20%D1%80%D0%B0%D0%B7%D0%BB%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B9%20%D0%B0%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%20%D0%BD%D0%B5%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%B5%D0%BD.%20%D0%97%D0%B0%20%D0%BE%D0%B4%D0%BD%D1%83%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8E%20%D0%BE%D0%BD%20%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%B5%D0%BD%20%D1%80%D0%B0%D0%B7%D0%BB%D0%B8%D1%82%D1%8C%20%D0%BF%D0%BE%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%BC%D1%83%20%D0%BB%D0%B8%D1%82%D1%80%D1%83%20%D0%BA%D0%B8%D1%81%D0%BB%D0%BE%D1%82%D1%8B%20%D0%B2%20%D0%BA%D0%B0%D0%B6%D0%B4%D1%8B%D0%B9%20%D0%B8%D0%B7%20%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D1%85%20k%20(1%20%E2%89%A4%20k%20%E2%89%A4%20n)%20%D1%80%D0%B5%D0%B7%D0%B5%D1%80%D0%B2%D1%83%D0%B0%D1%80%D0%BE%D0%B2.):
> К сожалению, разливающий аппарат несовершенен. За одну операцию он способен разлить по одному литру кислоты в каждый из первых k (1 ≤ k ≤ n) резервуаров. 

### Что это значит?
Это значит, что мы не можем заливать справа налево, только принудительно заливая в каждую из емкости по ходу из первых k резервуаров, у нас их 3 - `3 2 1`.
Соответственно аппарат должен идти в таком порядке `3 - 2 - 1` иначе разливать, ему не позволяет механизм.
При равном разлитии n-го количества литров, в случае когда слева от числа стоит большее его число, уровнять емкости **невозможно**
